#!/usr/bin/env bash
# req_status.sh - requirements implementation ledger for a spec-driven project.   VERSION: v3
#
# Scans the repo and prints a Markdown ledger of every REQ-ID: whether its plan is
# approved, its reviewer verdict, whether it is merged to the base branch, its GitHub Issue
# and PR, and which test cases (TC-IDs) exist for it. Project-agnostic: it relies only on the kit's
# conventions (docs/plans/<REQ>.md with a Status line, feat(<REQ>) commits, REQ and
# TC IDs named in tests/).
#
# Usage (from anywhere inside the repo):
#   bash scripts/req_status.sh                                  # print to stdout
#   bash scripts/req_status.sh -o docs/REQUIREMENTS_STATUS.md   # write to a file
#   bash scripts/req_status.sh --strict                         # exit 1 if a merged REQ has no tests (CI)
#
# Docs whose first line is "Status: TEMPLATE" are ignored, so placeholder REQ-IDs in
# unfilled templates are not reported as real requirements.
#
# Needs: git. Uses gh if available (Issue/PR state); degrades gracefully without it.
# v2: skips TEMPLATE docs, shows plan approved/draft, adds --strict, finds repo root.
# v3: Review column from docs/reviews/<REQ>.md (approved / changes / -). Reported, not enforced.
set -uo pipefail

OUT=""; STRICT=0
while [ $# -gt 0 ]; do
  case "$1" in
    -o) OUT="${2:?-o needs a path}"; shift 2 ;;
    --strict) STRICT=1; shift ;;
    -h|--help) sed -n '2,20p' "$0"; exit 0 ;;
    *) echo "unknown option: $1 (try --help)" >&2; exit 2 ;;
  esac
done

ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || { echo "ERROR : not inside a git repo" >&2; exit 2; }
cd "$ROOT" || exit 2

# ---- locate base branch ----
BASE=""
for ref in origin/main origin/master main master; do
  git rev-parse --verify -q "$ref" >/dev/null 2>&1 && { BASE="$ref"; break; }
done
LOGREF="${BASE:-HEAD}"

HAVE_GH=0
command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1 && HAVE_GH=1
# In CI, gh works with GH_TOKEN even when "gh auth status" is quiet about it.
[ "$HAVE_GH" = 0 ] && command -v gh >/dev/null 2>&1 && [ -n "${GH_TOKEN:-}" ] && HAVE_GH=1

# ---- discover REQ-IDs: non-template docs + commits on the base branch ----
doc_files=""
if [ -d docs ]; then
  while IFS= read -r f; do
    case "$f" in docs/REQUIREMENTS_STATUS.md|docs/plans/_TEMPLATE.md|docs/reviews/*) continue ;; esac
    head -1 "$f" | grep -q '^Status: TEMPLATE' && continue
    doc_files="${doc_files}${f}
"
  done < <(find docs -type f -name '*.md' | sort)
fi

reqs="$( {
  [ -n "$doc_files" ] && printf '%s' "$doc_files" | xargs grep -hoE 'REQ-[0-9]{3}' 2>/dev/null
  git log "$LOGREF" --oneline 2>/dev/null | grep -oE 'REQ-[0-9]{3}'
} | sort -u )"

emit() { if [ -n "$OUT" ]; then printf '%s\n' "$*" >>"$OUT"; else printf '%s\n' "$*"; fi; }
[ -n "$OUT" ] && { mkdir -p "$(dirname "$OUT")"; : > "$OUT"; }

total=0; done_n=0; untested_merged=""; unreviewed_merged=""
rows=""

for req in $reqs; do
  total=$((total+1))

  # plan: approved / draft / none
  pf="docs/plans/${req}.md"
  if [ -f "$pf" ]; then
    if head -1 "$pf" | grep -q '^Status: APPROVED'; then plan="approved"; else plan="draft"; fi
  else
    plan="-"
  fi

  # reviewer verdict: approved / changes / none
  rf="docs/reviews/${req}.md"
  review="-"
  if [ -f "$rf" ]; then
    rl="$(grep -m1 -v '^[[:space:]]*$' "$rf")"
    case "$rl" in
      "Verdict: APPROVE"*) review="approved" ;;
      "Verdict: CHANGES REQUESTED"*) review="changes" ;;
      *) review="?" ;;
    esac
  fi

  # merged to base? (feat|fix conventional commit)
  hit="$(git log -E --oneline --grep="(feat|fix)\(${req}\)" "$LOGREF" 2>/dev/null | head -1)"
  if [ -n "$hit" ]; then status="merged"; done_n=$((done_n+1)); else status="pending"; fi

  # Issue + PR via gh
  issue="-"; pr="-"
  if [ "$HAVE_GH" = 1 ]; then
    isn="$(gh issue list --search "$req in:title" --state all --json number,state --jq '.[0] | "#\(.number) (\(.state|ascii_downcase))"' 2>/dev/null)"
    [ -n "$isn" ] && [ "$isn" != "#null (null)" ] && issue="$isn"
    prn="$(gh pr list --search "$req in:title" --state all --json number,state --jq '.[0] | "#\(.number) (\(.state|ascii_downcase))"' 2>/dev/null)"
    [ -n "$prn" ] && [ "$prn" != "#null (null)" ] && pr="$prn"
  fi

  # test files referencing this REQ, and the TC-IDs in them
  tfiles="$(grep -rl "$req" tests 2>/dev/null || true)"
  ntests=0; tcs="-"
  if [ -n "$tfiles" ]; then
    ntests="$(printf '%s\n' "$tfiles" | grep -c . )"
    tcids="$(printf '%s\n' "$tfiles" | xargs grep -hoE 'TC-[0-9]+' 2>/dev/null | sort -u | paste -sd, - )"
    [ -n "$tcids" ] && tcs="$tcids"
  fi
  if [ "$status" = "merged" ] && [ "$review" != "approved" ]; then
    unreviewed_merged="${unreviewed_merged} ${req}"
  fi
  if [ "$status" = "merged" ] && [ "$ntests" -eq 0 ]; then
    untested_merged="${untested_merged} ${req}"
  fi

  rows="${rows}| ${req} | ${plan} | ${review} | ${status} | ${issue} | ${pr} | ${ntests} | ${tcs} |
"
done

# ---- write the report ----
emit "<!-- AUTO-GENERATED by scripts/req_status.sh. Do not edit by hand. -->"
emit "# Requirements Implementation Log"
emit ""
emit "Generated: $(date '+%Y-%m-%d %H:%M') | Base: ${BASE:-<none, using HEAD>} | gh: $([ $HAVE_GH = 1 ] && echo on || echo off)"
emit ""
emit "Summary: **${total} requirements** | **${done_n} merged** | **$((total-done_n)) pending**"
emit ""
if [ "$total" -eq 0 ]; then
  emit "No REQ-IDs found yet (template docs are ignored until their Status line changes)."
else
  emit "| REQ-ID | Plan | Review | Status | Issue | PR | Test files | TC-IDs in tests |"
  emit "|--------|------|--------|--------|-------|----|-----------|-----------------|"
  if [ -n "$OUT" ]; then printf '%s' "$rows" >>"$OUT"; else printf '%s' "$rows"; fi
fi

if [ -n "$unreviewed_merged" ]; then
  emit ""
  emit "**UNREVIEWED:** merged without a reviewer APPROVE:${unreviewed_merged} (blocks release, checklist A7)"
fi

if [ -n "$untested_merged" ]; then
  emit ""
  emit "**UNVERIFIED:** merged with no test files:${untested_merged}"
fi

[ -n "$OUT" ] && echo "wrote $OUT"

if [ "$STRICT" = 1 ] && [ -n "$untested_merged" ]; then
  echo "ERROR : --strict: merged REQ-IDs with no tests:${untested_merged}" >&2
  exit 1
fi
exit 0
